# Generated by Django 5.0 on 2023-12-08 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='messages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='thread.messages'),
        ),
    ]
