# Generated by Django 5.0 on 2023-12-08 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_thread_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='content',
            field=models.TextField(default='Hello', verbose_name='content of message'),
        ),
        migrations.AddField(
            model_name='messages',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_user_messages', to='thread.thread'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='messages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='thread_messages', to='thread.messages'),
        ),
    ]
