# Generated by Django 5.0 on 2023-12-09 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0005_alter_messages_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='messages',
        ),
        migrations.AddField(
            model_name='messages',
            name='messages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='thread.thread'),
        ),
    ]
