# Generated by Django 5.0 on 2023-12-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0006_remove_thread_messages_messages_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='messages',
            new_name='thread',
        ),
    ]
