# Generated by Django 5.0 on 2023-12-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0007_rename_messages_messages_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='send_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
