# Generated by Django 5.0 on 2023-12-11 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0008_messages_send_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='thread.thread'),
        ),
    ]
